{% set name = "dagster-dask" %}
{% set version = "0.6.7" %}

package:
  name: "{{ name.replace('-', '_') }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: cd8312218c565261019e6707a70396a79c266922da9cf529c3f7c2bd606a5340

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3
    - setuptools
  run:
    - python >=3
    - bokeh
    - dagster {{ version}}.*
    - dagster_graphql  {{ version }}.*
    - dask >=1.2.2
    - distributed >=1.28.1

test:
  imports:
    - dagster_dask
  requires:
    - pip
  commands:
    - pip check

about:
  home: "https://github.com/dagster-io/dagster/tree/master/python_modules/dagster-dask"
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "Package for using Dask as Dagster's execution engine."

extra:
  recipe-maintainers:
    - conda-forge/dagster
