{% set name = "dagster_dask" %}
{% set version = "0.6.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 30546342a7c222b99164d0209dc6d20b35df2e9e82fdb5c53a7f2b58ee3d205f

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3,<3.8
    - setuptools
  run:
    - python >=3,<3.8
    - bokeh
    - dagster {{ version}}.*
    - dagster_graphql  {{ version }}.*
    - dask 1.2.2.*
    - distributed 1.28.1.*

test:
  imports:
    - dagster_dask
    - dagster_dask_tests

about:
  home: "https://github.com/dagster-io/dagster/tree/master/python_modules/dagster-dask"
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "Package for using Dask as Dagster's execution engine."

extra:
  recipe-maintainers:
    - xhochy
