{% set name = "dagster_dask" %}
{% set version = "0.6.7.post0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name|replace('_', '-') }}/{{ name|replace('_', '-') }}-{{ version }}.tar.gz"
  sha256: ceb5e171a8bcbfb4e3b0b93c19e8612121a921b1a2314e58698f666480614085

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3
    - setuptools
  run:
    - python >=3
    - bokeh
    - dagster {{ version}}.*
    - dagster_graphql  {{ version }}.*
    - dask >=1.2.2
    - distributed >=1.28.1

test:
  imports:
    - dagster_dask

about:
  home: "https://github.com/dagster-io/dagster/tree/master/python_modules/dagster-dask"
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "Package for using Dask as Dagster's execution engine."

extra:
  recipe-maintainers:
    - conda-forge/dagster
